version: "3.8"

services:
  postgres:
    container_name: postgres
    image: postgres:15.3-alpine
    restart: unless-stopped
    environment:
      - POSTGRES_DB=dog-db
      - POSTGRES_USER=dog
      - POSTGRES_PASSWORD=woof
    ports:
      - '5432:5432'
    volumes:
      - postgres:/var/lib/postgresql/data
  zipkin:
    container_name: zipkin
    image: openzipkin/zipkin
    restart: unless-stopped
    ports:
      - 9411:9411
volumes:
  postgres:
    driver: local
